# Generated by Django 4.2.1 on 2023-06-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('sexo', models.BooleanField(blank=True, null=True)),
                ('identidade_genero', models.CharField(blank=True, max_length=50, null=True)),
                ('filiacao', models.CharField(blank=True, max_length=50, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('rg', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cns', models.CharField(blank=True, max_length=50, null=True)),
                ('situacao_rua', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritivo', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='paciente.paciente')),
            ],
        ),
    ]
