# Generated by Django 4.2.1 on 2023-06-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade_acolhimento', '0001_initial'),
        ('paciente', '0003_evolucao_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='unidade_acolhimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unidade_acolhimento.unidadeacolhimento'),
        ),
    ]
